import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Scratch directory of the `remember` plugin, gitignored via
    // .remember/.gitignore. ESLint 9's flat config does not read .gitignore, so
    // without this it lints a throwaway file and `npm run lint` never reaches a
    // clean 0 problems — which trains people to ignore the output.
    ".remember/**",
    // Playwright run artifacts, regenerated by the e2e suite.
    "test-results/**",
    "playwright-report/**",
  ]),
  {
    rules: {
      // Allow intentionally-unused args/vars prefixed with `_`, and the common
      // `const { secret, ...rest } = obj` pattern for omitting a field.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          ignoreRestSiblings: true,
        },
      ],
    },
  },
  {
    // Node-based test files legitimately use require() for module-reset patterns.
    files: ["__tests__/**", "**/*.test.js"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
  {
    files: ['app/**/*.{ts,tsx}', 'lib/**/*.{ts,tsx}'],
    ignores: ['lib/data/**', 'lib/db.ts', 'lib/auth/identity.ts'],
    rules: {
      'no-restricted-imports': ['error', {
        // `patterns`, not `paths`. `paths` matches the literal specifier only, so
        // `../../lib/db` and `./db` walk straight through it — which is how
        // lib/auth.ts and lib/authz.ts evaded the first draft of this rule.
        patterns: [{
          // `**/db` is load-bearing and NOT redundant with `**/lib/db`. Verified
          // 2026-08-03: with only the four narrower patterns, a file two or more
          // levels inside lib/ — e.g. lib/authz/sub/x.ts importing '../../db' —
          // reaches lib/db.ts while matching none of them, defeating the ban for
          // exactly the class of file it exists to police. That is the same
          // "closed the instances, left the class open" mistake as the original
          // `paths` form, one level down.
          group: ['@/lib/db', '**/lib/db', '**/db', './db', '../db'],
          message: 'Tenant data goes through withOrg (lib/data/tenant.ts); non-tenant through identityDb (lib/data/identity.ts). See ADR-0001.',
        }, {
          // ADR-0002: the raw session is unreachable from application code.
          // `requireIdentity()` (lib/auth/identity.ts) is the one choke point —
          // it re-checks isActive/sessionEpoch/absolute-age against the
          // database on every call, which a cached `session.user.role` never
          // did. `lib/auth/identity.ts` itself is exempted via `ignores` above:
          // it is the sanctioned place this import is allowed.
          group: ['@/lib/auth', '**/lib/auth', './auth', '../auth'],
          importNames: ['auth'],
          message: 'Use requireIdentity() from lib/auth/identity.ts. See ADR-0002.',
        }],
      }],
      // `no-restricted-imports` only sees STATIC import declarations. Verified
      // 2026-08-03: `await import('../db')` and `require('../../lib/db')` both
      // walked through it untouched, so widening the specifier patterns closed
      // one more shape within one syntactic form and left two forms open. The
      // same two selectors are reused below for the `auth` ban, generalised
      // from `/(^|\/)db$/` to `/(^|\/)auth$/` — same gap, same fix.
      'no-restricted-syntax': ['error',
        {
          selector: "ImportExpression[source.value=/(^|\\u002F)db$/]",
          message: 'Tenant data goes through withOrg (lib/data/tenant.ts); non-tenant through identityDb. See ADR-0001.',
        },
        {
          selector: "CallExpression[callee.name='require'][arguments.0.value=/(^|\\u002F)db$/]",
          message: 'Tenant data goes through withOrg (lib/data/tenant.ts); non-tenant through identityDb. See ADR-0001.',
        },
        {
          selector: "ImportExpression[source.value=/(^|\\u002F)auth$/]",
          message: 'Use requireIdentity() from lib/auth/identity.ts. See ADR-0002.',
        },
        {
          selector: "CallExpression[callee.name='require'][arguments.0.value=/(^|\\u002F)auth$/]",
          message: 'Use requireIdentity() from lib/auth/identity.ts. See ADR-0002.',
        },
      ],
    },
  },
  {
    // D-089 / Task 5: `createOrgContext` mints an `OrgContext`, and an
    // `OrgContext` is only trustworthy when it was minted by
    // `requireOrgContext` — the one place that has proven the six facts
    // ADR-0001 requires before calling it. `lib/data/tenant.ts` is ignored
    // because it's the definition site (must be able to reference its own
    // export); `lib/auth/context.ts` is ignored because it is the sanctioned
    // caller. `__tests__/integration/org-context.test.ts` independently pins
    // this same invariant by enumerating importers from disk, so a change
    // here is checked twice rather than trusted to either alone.
    files: ['app/**/*.{ts,tsx}', 'lib/**/*.{ts,tsx}'],
    ignores: ['lib/data/tenant.ts', 'lib/auth/context.ts'],
    rules: {
      'no-restricted-imports': ['error', {
        patterns: [{
          group: ['@/lib/data/tenant', '**/lib/data/tenant', '**/data/tenant', './tenant', '../tenant', '../data/tenant'],
          importNames: ['createOrgContext'],
          message: 'createOrgContext may only be called by requireOrgContext (lib/auth/context.ts). See lib/data/tenant.ts and ADR-0001 (D-089).',
        }],
      }],
    },
  },
]);

export default eslintConfig;
