import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Scratch directory of the `remember` plugin, gitignored via
    // .remember/.gitignore. ESLint 9's flat config does not read .gitignore, so
    // without this it lints a throwaway file and `npm run lint` never reaches a
    // clean 0 problems — which trains people to ignore the output.
    ".remember/**",
    // Playwright run artifacts, regenerated by the e2e suite.
    "test-results/**",
    "playwright-report/**",
  ]),
  {
    rules: {
      // Allow intentionally-unused args/vars prefixed with `_`, and the common
      // `const { secret, ...rest } = obj` pattern for omitting a field.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          ignoreRestSiblings: true,
        },
      ],
    },
  },
  {
    // Node-based test files legitimately use require() for module-reset patterns.
    files: ["__tests__/**", "**/*.test.js"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
  {
    files: ['app/**/*.{ts,tsx}', 'lib/**/*.{ts,tsx}'],
    ignores: ['lib/data/**', 'lib/db.ts', 'lib/auth/identity.ts'],
    rules: {
      'no-restricted-imports': ['error', {
        // `patterns`, not `paths`. `paths` matches the literal specifier only, so
        // `../../lib/db` and `./db` walk straight through it — which is how
        // lib/auth.ts and lib/authz.ts evaded the first draft of this rule.
        patterns: [{
          // `**/db` is load-bearing and NOT redundant with `**/lib/db`. Verified
          // 2026-08-03: with only the four narrower patterns, a file two or more
          // levels inside lib/ — e.g. lib/authz/sub/x.ts importing '../../db' —
          // reaches lib/db.ts while matching none of them, defeating the ban for
          // exactly the class of file it exists to police. That is the same
          // "closed the instances, left the class open" mistake as the original
          // `paths` form, one level down.
          group: ['@/lib/db', '**/lib/db', '**/db', './db', '../db'],
          message: 'Tenant data goes through withOrg (lib/data/tenant.ts); non-tenant through identityDb (lib/data/identity.ts). See ADR-0001.',
        }, {
          // ADR-0002: the raw session is unreachable from application code.
          // `requireIdentity()` (lib/auth/identity.ts) is the one choke point —
          // it re-checks isActive/sessionEpoch/absolute-age against the
          // database on every call, which a cached `session.user.role` never
          // did. `lib/auth/identity.ts` itself is exempted via `ignores` above:
          // it is the sanctioned place this import is allowed.
          group: ['@/lib/auth', '**/lib/auth', './auth', '../auth'],
          importNames: ['auth'],
          message: 'Use requireIdentity() from lib/auth/identity.ts. See ADR-0002.',
        }],
      }],
      // `no-restricted-imports` only sees STATIC import declarations. Verified
      // 2026-08-03: `await import('../db')` and `require('../../lib/db')` both
      // walked through it untouched, so widening the specifier patterns closed
      // one more shape within one syntactic form and left two forms open. The
      // same two selectors are reused below for the `auth` ban, generalised
      // from `/(^|\/)db$/` to `/(^|\/)auth$/` — same gap, same fix.
      'no-restricted-syntax': ['error',
        {
          selector: "ImportExpression[source.value=/(^|\\u002F)db$/]",
          message: 'Tenant data goes through withOrg (lib/data/tenant.ts); non-tenant through identityDb. See ADR-0001.',
        },
        {
          selector: "CallExpression[callee.name='require'][arguments.0.value=/(^|\\u002F)db$/]",
          message: 'Tenant data goes through withOrg (lib/data/tenant.ts); non-tenant through identityDb. See ADR-0001.',
        },
        {
          selector: "ImportExpression[source.value=/(^|\\u002F)auth$/]",
          message: 'Use requireIdentity() from lib/auth/identity.ts. See ADR-0002.',
        },
        {
          selector: "CallExpression[callee.name='require'][arguments.0.value=/(^|\\u002F)auth$/]",
          message: 'Use requireIdentity() from lib/auth/identity.ts. See ADR-0002.',
        },
      ],
    },
  },
  {
    // Unported call sites still on the raw client, re-enumerated 2026-08-03.
    // Plan 1b deletes these entries one at a time as each moves to
    // withOrg/identityDb; when the list is empty, delete this block entirely.
    // Adding a NEW path here is a review failure, not a workaround.
    //
    // The `\\[id\\]` escaping is load-bearing, not noise. `files` entries are
    // globs, not literal paths: unescaped, `[id]` is a picomatch CHARACTER
    // CLASS matching the single character `i` or `d`, so it never matches a
    // Next.js dynamic-segment directory literally named `[id]`. Verified
    // 2026-08-03 — with plain `[id]` these same 8 entries silently missed and
    // `npm run lint` reported 8 errors; escaped, it reports 0.
    files: [
      'app/api/admin/users/\\[id\\]/role/route.ts',
      'app/api/assessments/\\[id\\]/complete/route.ts',
      'app/api/assessments/\\[id\\]/remediation/route.ts',
      'app/api/assessments/\\[id\\]/route.ts',
      'app/api/assessments/route.ts',
      'app/api/auth/register/route.ts',
      'app/api/projects/\\[id\\]/route.ts',
      'app/api/projects/route.ts',
      'app/api/reports/\\[id\\]/pdf/route.ts',
      'app/api/research/export/route.ts',
      'app/api/users/me/export/route.ts',
      'app/api/users/me/password/route.ts',
      'app/api/users/me/route.ts',
      'app/(authenticated)/admin/assessments/page.tsx',
      'app/(authenticated)/admin/settings/page.tsx',
      'app/(authenticated)/admin/users/page.tsx',
      'app/(authenticated)/dashboard/page.tsx',
      'app/(authenticated)/projects/\\[id\\]/compare/page.tsx',
      'app/(authenticated)/projects/\\[id\\]/page.tsx',
      'app/(authenticated)/projects/page.tsx',
      'lib/auth.ts',   // reads User at login — moves to identityDb in Plan 1b
      'lib/authz.ts',  // deleted in Plan 1b: its ownership premise is wrong under tenancy
    ],
    rules: { 'no-restricted-imports': 'off', 'no-restricted-syntax': 'off' },
  },
]);

export default eslintConfig;
