import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 10 },
  header: { marginBottom: 20, borderBottom: '2 solid #C06014', paddingBottom: 10 },
  title: { fontSize: 20, fontFamily: 'Helvetica-Bold', color: '#1a1a2e' },
  subtitle: { fontSize: 12, color: '#666', marginTop: 4 },
  section: { marginTop: 16, marginBottom: 8 },
  sectionTitle: { fontSize: 14, fontFamily: 'Helvetica-Bold', marginBottom: 8, color: '#C06014' },
  scoreBox: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  scoreItem: { padding: 8, backgroundColor: '#f5f5f5', borderRadius: 4, width: '30%', textAlign: 'center' },
  scoreValue: { fontSize: 24, fontFamily: 'Helvetica-Bold' },
  scoreLabel: { fontSize: 8, color: '#666' },
  areaRow: { flexDirection: 'row', padding: 6, borderBottom: '1 solid #eee' },
  areaName: { width: '50%' },
  areaScore: { width: '25%', textAlign: 'center' },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 8, color: '#999', textAlign: 'center' },
});

interface ReportPdfProps {
  reportData: any;
  projectName: string;
  assessorName: string;
  assessmentDate: string;
}

export function ReportPdf({ reportData, projectName, assessorName, assessmentDate }: ReportPdfProps) {
  const { overallScore, completedStages, principleScores } = reportData;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Responsible AI Readiness Report</Text>
          <Text style={styles.subtitle}>{projectName} {'\u00B7'} {assessorName} {'\u00B7'} {assessmentDate}</Text>
        </View>

        <View style={styles.scoreBox}>
          <View style={styles.scoreItem}>
            <Text style={styles.scoreValue}>{Math.round(overallScore)}%</Text>
            <Text style={styles.scoreLabel}>Overall Score</Text>
          </View>
          <View style={styles.scoreItem}>
            <Text style={styles.scoreValue}>{completedStages.length}/3</Text>
            <Text style={styles.scoreLabel}>Stages Assessed</Text>
          </View>
          <View style={styles.scoreItem}>
            <Text style={styles.scoreValue}>
              {overallScore >= 75 ? 'Strong' : overallScore >= 50 ? 'Developing' : overallScore >= 25 ? 'Needs Work' : 'Critical'}
            </Text>
            <Text style={styles.scoreLabel}>Maturity Level</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Principle Scores</Text>
          {completedStages.map((stage: string) => {
            const scores = principleScores[stage] || {};
            return (
              <View key={stage} style={{ marginBottom: 8 }}>
                <Text style={{ fontFamily: 'Helvetica-Bold', marginBottom: 4 }}>
                  {stage.replace(/-/g, ' ').replace(/\b\w/g, (l: string) => l.toUpperCase())}
                </Text>
                {Object.entries(scores).map(([principle, score]) => (
                  <View key={principle} style={styles.areaRow}>
                    <Text style={styles.areaName}>{principle}</Text>
                    <Text style={styles.areaScore}>{Math.round(score as number)}%</Text>
                  </View>
                ))}
              </View>
            );
          })}
        </View>

        <Text style={styles.footer}>Generated by MAK-AI Responsible AI Toolkit {'\u00B7'} {assessmentDate}</Text>
      </Page>
    </Document>
  );
}
